# Visit the Docker compose reference guide for more information
# https://docs.docker.com/compose/compose-file/

# build application services
version: '0.1'
services:
  # create container
  ubuntudevcontainer:
    # set image name
    image: ubuntu_for_scrapy
    # set build context to local dockerfile
    build:
      context: ./.devcontainer
    # bind host to container to persist file changes
    volumes:
      - .:/doral_prospecting:cached
    # enable allocation of terminal to container
    tty: true
    # keep standard input open on container
    stdin_open: true
    # overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"
    